name: Sync from DockerHub to GHCR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  sync-images:
    name: Sync tagged images from DockerHub to GHCR
    runs-on: ubuntu-24.04
    steps:
      - name: Sync images
        uses: it-bens/container-registry-sync-action@2868df2645b2b4d0a84d3393c3c5066b2c5b6931 # v0.5.1
        with:
          sourceRepository: 'dockware/proxy'
          loginToSourceRepository: 'true'
          sourceRepositoryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          sourceRepositoryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          targetRepository: 'ghcr.io/dockware-mirror/proxy'
          loginToTargetRepository: 'true'
          targetRepositoryUsername: ${{ github.actor }}
          targetRepositoryPassword: ${{ secrets.GITHUB_TOKEN }}
          tags: '*'
          regClientConcurrency: 2
